sudo: required

services: 
  - docker

arch:
  repos:
  packages:
    #FIFE: (from AUR)
    # - fife-git
    # - fifechan-git
    # Style tests:
    # - python-isort
    # - python-pycodestyle
    # Misc. Required for tests.
#    - python-pytesti
#    - python-pytest-isort
#    - python-pytest-cov
#    - python-greenlet
    #Pytest is currently broken in python 3.7 (default for arch)
#    - python36
  script:
    - TERM=screen
    - echo -e "travis_fold:start:MORE INIT\033[33;1m$2\033[0m"
    #Moving packages into this fold.
    - echo "Install Packages:"
    - yay -S fife-git --noconfirm 2>&1 > tmp.log && echo "Fife-git installed fine." || ( echo "Fife-git failed:" ; cat tmp.log )
    - yay -S fifechan-git --noconfirm 2>&1 > tmp.log && echo "FifeChan-git installed fine." || ( echo "FifeChan-git failed:" ; cat tmp.log )
    - yay -S python36 python-isort  python-pycodestyle --noconfirm 2>&1 > tmp.log && echo "Python installed fine." || ( echo "Python failed:" ; cat tmp.log )
    #Chown for collections
    - sudo chown $UID $TRAVIS_BUILD_DIR -R
    #Fix too-up-to-date python
    - python3.6 -m venv py36
    - source py36/bin/activate
    - pip install -r requirements.txt
    #Regular build/testing.
    - echo -e "\ntravis_fold:end:MORE INIT\r"
    - python3 -c 'from fife import fife; print(fife.getVersion())'
    - isort -c -rc horizons tests *.py
    - pycodestyle horizons tests *.py development
    - COVERAGE_FILE=.coverage.nongui pytest --verbose --cov --cov-report= -rs
    - RUNCOV=1 pytest --gui-tests tests/gui --verbose --cov --cov-report= -rs

after_success: 
  - coverage combine
  - coveralls

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
