sudo: required

services: 
  - docker

arch:
  repos:
  packages:
  script:
    - echo -e "travis_fold:start:MORE_INIT\033[33;1mMORE_INIT\033[0m"
    #Helpers
    - export TERM=screen
    - function TEXT_SETRED() { echo -en '\033[0;31m' ; }
    - function TEXT_SETGREEN() { echo -en '\033[0;32m' ; }
    - function TEXT_SETYELLOW() { echo -en '\033[0;33m' ; }
    - function TEXT_RESET() { echo -en '\033[0m' ; }
    - set -o pipefail
    - function ONELINE() { while read line; do echo -ne "\033[2K\r"; echo -n $line ; done ; echo -ne "\033[2K\r" ; }
    - function MISCWRAPPER() { NAME=$1; shift; ( eval $@ ) 2>&1 | tee tmp.log | ONELINE && TEXT_SETGREEN && echo $NAME" PASSED" && TEXT_RESET || ( TEXT_SETRED ; echo $NAME" FAILED" ; cat tmp.log ; TEXT_RESET ; exit 1 ) }
    - function INSTALLWRAPPER() { MISCWRAPPER Installing\ $1 yay -S --noconfirm --color always $@ ; }
    

    - echo "Install Packages:"
    - PYTHON_PKGS="python python-isort python-pycodestyle python-pytest python-pytest-isort python-pytest-cov python-coverage python-greenlet python-yaml python-polib"
    - INSTALLWRAPPER fifechan-git fife-git
    - INSTALLWRAPPER python $PYTHON_PKGS
    - INSTALLWRAPPER xorg-server-xvfb
#    - MISCWRAPPER "PIP INSTALLS" sudo pip install -r requirements.txt
    
    #Chown for collections
    - sudo chown $UID $TRAVIS_BUILD_DIR -R

    #Fix too-up-to-date python (There is a patch to fix needing this)
    # - python3.6 -m venv py36
    # - source py36/bin/activate
    # - pip install -r requirements.txt

    - echo -e "\ntravis_fold:end:MORE_INIT\r"

    #Regular build/testing.
    - python3 -c 'from fife import fife; print(fife.getVersion())'
    - TEXT_SETRED ; isort -c -rc horizons tests *.py ; TEXT_RESET;
    - TEXT_SETRED ; pycodestyle horizons tests *.py development ; TEXT_RESET;
    - COVERAGE_FILE=.coverage.nongui pytest --verbose --cov --cov-report= -rs --color=yes
    - Xvfb :99 +xinerama +iglx & XPID=$!
    - sleep 10 
    - DISPLAY=:99 RUNCOV=1 pytest --gui-tests tests/gui --verbose --cov --cov-report= -rs --color=yes
    - kill -9 $XPID

after_success: 
  - coverage combine
  - coveralls

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
