sudo: required

services: 
  - docker

arch:
  repos:
  packages:
    - fife-git
    - fifechan-git 
    - python-isort
    - python-pytest
    - python-pytest-isort
    - python-pycodestyle
#  script:
#    - "./build_script.sh"
#

script:
  - python3 -c 'from fife import fife; print(fife.getVersion())'
  - isort -c -rc horizons tests *.py
  - pycodestyle horizons tests *.py development
  - COVERAGE_FILE=.coverage.nongui pytest --verbose --cov --cov-report= -rs
  - RUNCOV=1 pytest --gui-tests tests/gui --verbose --cov --cov-report= -rs

after_success: 
  - coverage combine
  - coveralls

