sudo: required

services: 
  - docker

arch:
  repos:
  packages:
    #FIFE: (from AUR)
    - fife-git
    - fifechan-git
    # Style tests:
    - python-isort
    - python-pycodestyle
    # Misc. Required for tests.
    - python-pytest
    - python-pytest-isort
    - python-pytest-cov
    - python-greenlet
    #Pytest is currently broken in python 3.7 (default for arch)
    - python36
  script:
    - TERM=screen
    - echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"
    - sudo chown $UID $TRAVIS_BUILD_DIR -R
    - python3.6 -m venv py36
    - source py36/bin/activate
    - pip install -r requirements.txt
    - echo -e "\ntravis_fold:end:$1\r"
    - python3 -c 'from fife import fife; print(fife.getVersion())'
    - isort -c -rc horizons tests *.py
    - pycodestyle horizons tests *.py development
    - COVERAGE_FILE=.coverage.nongui pytest --verbose --cov --cov-report= -rs
    - RUNCOV=1 pytest --gui-tests tests/gui --verbose --cov --cov-report= -rs

after_success: 
  - coverage combine
  - coveralls

script:
  - "curl -s https://raw.githubusercontent.com/ttoocs/arch-travis/master/arch-travis.sh | bash"
